# RECIPES
create_recipe:
    path: /new_recipe
    controller: App\Controller\RecipeController::createRecipe
    methods:
        - POST
read_recipe:
    path: /recipe/{id}
    controller: App\Controller\RecipeController::showRecipe
    methods:
        - GET
update_recipe:
    path: /update_recipe/{id}
    controller: App\Controller\RecipeController::updateRecipe
    methods:
        - PUT
delete_recipe:
    path: /delete_recipe/{id}
    controller: App\Controller\RecipeController::deleteRecipe
    methods:
        - DELETE
show_all_recipes:
    path: /recipes
    controller: App\Controller\RecipeController::listAll
    methods:
        - GET
show_all_user_recipes:
    path: /recipes/{userId}
    controller: App\Controller\RecipeController::listUserRecipes
    methods:
        - GET
followed_users_recipes:
    path: /followedUsersRecipes
    controller: App\Controller\RecipeController::recipesFromUsersYouFollow
    methods:
        - GET
store_recipe_picture:
    path: /store_recipe_pic/{id}
    controller: App\Controller\RecipeController::storePicture
    methods:
        - POST
get_recipe_picture:
    path: /get_recipe_pic/{id}
    controller: App\Controller\RecipeController::getPicture
    methods:
        - GET
add_step:
    path: /add_step/recipe/{id}
    controller: App\Controller\StepController::addStep
    methods:
        - POST
add_ingredient:
    path: /add_ingredient/recipe/{id}
    controller: App\Controller\IngredientController::addIngredient
    methods:
        - POST

# RATES
create_rate:
    path: /new_rate/{recipe_id}
    controller: App\Controller\RateController::newRate
    methods:
        - POST
show_rate:
    path: /rate/{id}
    controller: App\Controller\RateController::showRate
    methods:
        - GET
mostra_avaliacoes_receita:
    path: /rate/recipe/{id}
    controller: App\Controller\RateController::ratesFromRecipe
    methods:
        - GET

# USERS
create_user:
    path: /sign_up
    controller: App\Controller\UserController::newUser
    methods:
        - POST
read_user:
    path: /find_user/{id}
    controller: App\Controller\UserController::showUser
    methods:
        - GET
update_user:
    path: /update_user
    controller: App\Controller\UserController::updateUser
    methods:
        - PUT
delete_user:
    path: /delete_user
    controller: App\Controller\UserController::deleteUser
    methods:
        - DELETE
change_password:
    path: /change_password
    controller: App\Controller\UserController::setPassword
    methods:
        - PUT
login:
    path: /login
    controller: App\Controller\UserController::login
    methods:
        - POST
get_cred:
    path: /cred
    controller: App\Controller\UserController::getCred
    methods:
        - GET
follow:
    path: /follow
    controller: App\Controller\UserController::startFollowing
    methods:
        - POST
get_followers:
    path: /followers
    controller: App\Controller\UserController::getAllFollowers
    methods:
        - GET
store_profile_pic:
    path: /pic
    controller: App\Controller\UserController::storePicture
    methods:
        - POST
get_profile_picture:
    path: /get_pic/{id}
    controller: App\Controller\UserController::getPicture
    methods:
        - GET