# RECEITAS
mostra_receita:
    path: /recipe/{id}
    controller: App\Controller\RecipeController::mostraReceita
    methods:
        - GET
mostra_todas:
    path: /recipes
    controller: App\Controller\RecipeController::listaTodas
    methods:
        - GET
mostra_todas_usuario:
    path: /recipes/{userId}
    controller: App\Controller\RecipeController::listaReceitasUsuario
    methods:
        - GET
nova_receita:
    path: /recipe
    controller: App\Controller\RecipeController::novaReceita
    methods:
        - POST
remove_receita:
    path: /recipe/{id}
    controller: App\Controller\RecipeController::removeReceita
    methods:
        - DELETE
receitas_de_seguidos:
    path: /followedUsersRecipes
    controller: App\Controller\RecipeController::recipesFromUsersYouFollow
    methods:
        - GET

# AVALIÇÕES
nova_avaliacao:
    path: /rate
    controller: App\Controller\AvaliacaoController::novaAvaliacao
    methods:
        - POST
mostra_todas_avaliacoes:
    path: /rates
    controller: App\Controller\AvaliacaoController::listaTodas
    methods:
        - GET
mostra_avaliacoes_receita:
    path: /rates/{id}
    controller: App\Controller\AvaliacaoController::ratesFromRecipe
    methods:
        - GET

# USUÁRIOS
login:
    path: /login
    controller: App\Controller\UserController::login
    methods:
        - POST
new_user:
    path: /sign_up
    controller: App\Controller\UserController::newUser
    methods:
        - POST
find_user:
    path: /find/{id}
    controller: App\Controller\UserController::findEmailById
    methods:
        - GET
get_cred:
    path: /cred
    controller: App\Controller\UserController::getCred
    methods:
        - GET
follow:
    path: /follow
    controller: App\Controller\UserController::startFollowing
    methods:
        - POST
get_followers:
    path: /followers
    controller: App\Controller\UserController::getAllFollowers
    methods:
        - GET
store_profile_pic:
    path: /pic
    controller: App\Controller\UserController::storePicture
    methods:
        - POST
get_profile_picture:
    path: /getpic/{id}
    controller: App\Controller\UserController::getPicture
    methods:
        - GET
