#index:
#    path: /
#    controller: App\Controller\DefaultController::index
mostra_receita:
    path: /recipe/{id}
    controller: App\Controller\RecipeController::mostraReceita
    methods:
        - GET
mostra_todas:
    path: /recipes
    controller: App\Controller\RecipeController::listaTodas
    methods:
        - GET
nova_receita:
    path: /recipe
    controller: App\Controller\RecipeController::novaReceita
    methods:
        - POST
nova_avaliacao:
    path: /rate
    controller: App\Controller\AvaliacaoController::novaAvaliacao
    methods:
        - POST
mostra_todas_avaliacoes:
    path: /rates
    controller: App\Controller\AvaliacaoController::listaTodas
    methods:
        - GET