# RECEITAS
create_recipe:
    path: /new_recipe
    controller: App\Controller\RecipeController::createRecipe
    methods:
        - POST
show_recipe:
    path: /recipe/{id}
    controller: App\Controller\RecipeController::showRecipe
    methods:
        - GET
update_recipe:
    path: /update_recipe
    controller: App\Controller\RecipeController::updateRecipe
    methods:
        - PUT
delete_recipe:
    path: /delete_recipe/{id}
    controller: App\Controller\RecipeController::deleteRecipe
    methods:
        - DELETE
show_all_recipes:
    path: /recipes
    controller: App\Controller\RecipeController::listAll
    methods:
        - GET
show_all_user_recipes:
    path: /recipes/{userId}
    controller: App\Controller\RecipeController::listUserRecipes
    methods:
        - GET
followed_users_recipes:
    path: /followedUsersRecipes
    controller: App\Controller\RecipeController::recipesFromUsersYouFollow
    methods:
        - GET
store_recipe_picture:
    path: /store_recipe_pic/{id}
    controller: App\Controller\RecipeController::storePicture
    methods:
        - POST
get_recipe_picture:
    path: /get_recipe_pic/{id}
    controller: App\Controller\RecipeController::getPicture
    methods:
        - GET

# AVALIAÇÕES
nova_avaliacao:
    path: /rate
    controller: App\Controller\AvaliacaoController::novaAvaliacao
    methods:
        - POST
mostra_todas_avaliacoes:
    path: /rates
    controller: App\Controller\AvaliacaoController::listaTodas
    methods:
        - GET
mostra_avaliacoes_receita:
    path: /rates/{id}
    controller: App\Controller\AvaliacaoController::ratesFromRecipe
    methods:
        - GET

# USUÁRIOS
login:
    path: /login
    controller: App\Controller\UserController::login
    methods:
        - POST
new_user:
    path: /sign_up
    controller: App\Controller\UserController::newUser
    methods:
        - POST
find_user:
    path: /find_user/{id}
    controller: App\Controller\UserController::findEmailById
    methods:
        - GET
get_cred:
    path: /cred
    controller: App\Controller\UserController::getCred
    methods:
        - GET
follow:
    path: /follow
    controller: App\Controller\UserController::startFollowing
    methods:
        - POST
get_followers:
    path: /followers
    controller: App\Controller\UserController::getAllFollowers
    methods:
        - GET
store_profile_pic:
    path: /pic
    controller: App\Controller\UserController::storePicture
    methods:
        - POST
get_profile_picture:
    path: /get_pic/{id}
    controller: App\Controller\UserController::getPicture
    methods:
        - GET